# Generated by Django 4.0.2 on 2022-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
