# Generated by Django 4.0.2 on 2022-03-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_profile_datecreate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Users'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='state',
        ),
    ]
