# Generated by Django 4.0.2 on 2022-03-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_profile_options_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User'},
        ),
    ]
